# Inspect Polyhouse Sensor Data

Load the raw sensor CSV, inspect its structure, and display the saved Parquet snapshot for comparison.

## Column Definitions

| Column | Definition | Unit |
| --- | --- | --- |
| `timestamp` | Date of the sensor readings and daily yield | Date |
| `temperature_c` | Polyhouse air temperature | Degrees Celsius (°C) |
| `humidity_pct` | Relative humidity inside the polyhouse | Percent (%) |
| `co2_ppm` | Carbon dioxide concentration | Parts per million (ppm) |
| `yield_kg` | Daily mushroom yield (prediction target) | Kilograms (kg) |

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

# Find the project root whether Jupyter starts at the root or in notebooks/.
project_root = next(
    (
        candidate
        for candidate in (Path.cwd(), *Path.cwd().parents)
        if (candidate / "data" / "raw" / "polyhouse_sensors.csv").is_file()
    ),
    None,
)
if project_root is None:
    raise FileNotFoundError(
        "Could not find data/raw/polyhouse_sensors.csv. Run the sample generator first."
    )

raw_path = project_root / "data" / "raw" / "polyhouse_sensors.csv"
snapshot_path = project_root / "data" / "interim" / "01_loaded.parquet"
header = pd.read_csv(raw_path, nrows=0)
date_columns = ["timestamp"] if "timestamp" in header.columns else []
df = pd.read_csv(raw_path, parse_dates=date_columns)

## Raw CSV Inspection

In [2]:
print("Shape:", df.shape)
print("\nData types:")
display(df.dtypes.to_frame(name="dtype"))
print("\nDataFrame info:")
df.info()
print("\nFirst five rows:")
display(df.head())
print("\nDataset:")
display(df)

Shape: (365, 5)

Data types:

                        dtype
timestamp      datetime64[us]
temperature_c         float64
humidity_pct          float64
co2_ppm               float64
yield_kg              float64

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      365 non-null    datetime64[us]
 1   temperature_c  365 non-null    float64
 2   humidity_pct   365 non-null    float64
 3   co2_ppm        365 non-null    float64
 4   yield_kg       365 non-null    float64
dtypes: datetime64[us](1), float64(4)
memory usage: 14.4 KB

First five rows:

   timestamp  temperature_c  humidity_pct  co2_ppm  yield_kg
0 2024-01-01          22.46          91.4    936.0     18.05
1 2024-01-02          20.44          84.8    905.0     17.35
2 2024-01-03          23.13          84.5    944.0     17.52
3 2024-01-04          23.41          87.6    885.0     18.12
4 2024-01-05          19.07          89.5    922.0     16.98

Dataset:

     timestamp  temperature_c  humidity_pct  co2_ppm  yield_kg
0   2024-01-01          22.46          91.4    936.0     18.05
1   2024-01-02          20.44          84.8    905.0     17.35
2   2024-01-03          23.13          84.5    944.0     17.52
3   2024-01-04          23.41          87.6    885.0     18.12
4   2024-01-05          19.07          89.5    922.0     16.98
..         ...            ...           ...      ...       ...
360 2024-12-26          21.77          91.4    852.0     17.34
361 2024-12-27          22.58          87.8    901.0     18.51
362 2024-12-28          23.50          89.3    964.0     17.63
363 2024-12-29          20.41          83.6    914.0     17.37
364 2024-12-30          21.81          83.6    848.0     17.21

[365 rows x 5 columns]

## Saved Snapshot

In [3]:
if snapshot_path.is_file():
    snapshot_df = pd.read_parquet(snapshot_path)
    print("Parquet snapshot shape:", snapshot_df.shape)
    display(snapshot_df.head())
else:
    print("Parquet snapshot not found. Run src/ingest.py to create it.")

Parquet snapshot shape: (365, 5)

   timestamp  temperature_c  humidity_pct  co2_ppm  yield_kg
0 2024-01-01          22.46          91.4    936.0     18.05
1 2024-01-02          20.44          84.8    905.0     17.35
2 2024-01-03          23.13          84.5    944.0     17.52
3 2024-01-04          23.41          87.6    885.0     18.12
4 2024-01-05          19.07          89.5    922.0     16.98